Search event
thiagoferreiraw/mixapp pull request #39
Opened 2017-11-15 23:23 UTC by fnscoder

2017-11-16 01:33 UTC, thiagoferreiraw requested changes
Good work! Just a few changes to go!

2017-11-16 01:33 UTC, thiagoferreiraw commented on events/templates/events/search_events.html
> +            <form method="post">
Formulários de pesquisa é padrão usar o método GET; Assim, o usuário mantem a pesquisa na url, tipo /events?category=1&city=2

2017-11-16 01:33 UTC, thiagoferreiraw commented on events/templates/events/search_events.html
> +                        <option value="{{ category.name }}">{{ category.name }}</option>
Usar o Form do django pra fazer isso; 
Dessa forma, tem a vantagem de manter o valor digitado antes de submeter a pesquisa, além de padronizar com o resto do projeto. 
https://docs.djangoproject.com/en/1.11/ref/forms/

2017-11-16 01:33 UTC, thiagoferreiraw commented on events/templates/events/search_events.html
> +                        <option value="{{ city.description }}">{{ city.description }}</option>
Usar form django...

2017-11-16 01:33 UTC, thiagoferreiraw commented on events/templates/events/search_events.html
> +    {% if request.method == "POST" %}
Como conversamos, vamos exibir todos os eventos sempre que o usuario entrar na tela, então nao vai ter necessidade desse IF mais;

2017-11-16 01:33 UTC, thiagoferreiraw commented on events/templates/events/search_events.html
> +            <p>Sorry! We don't have any event in this city or category at this moment.</p>
Pode colocar essa mensagem dentro da tag {% empty %}, um pouco acima. O djagno já suporta esses casos; Aí poderia tirar o {% if events %};

2017-11-16 01:33 UTC, thiagoferreiraw commented on events/tests/test_views.py
> +class SearchEventViewTests(TestCase):
Como conversamos, adicionar a fixture e realizar os testes da filtragem dos eventos

2017-11-16 01:33 UTC, thiagoferreiraw commented on events/views/search_event_view.py
> +            category = Category.objects.get(name=category)
Buscar a categoria e cidade não é confiável; Quando fizer a alteração para usar o Form do django, vc vai receber pelo request o ID direto da categoria, aí vai poder adicionar direto no queryset de eventos, sem fazer esse passo;

2017-11-16 23:25 UTC, thiagoferreiraw commented on events/views/search_event_view.py
> +        events = Event.objects.all()
Aqui, precisa filtrar apenas igual ou maior que hoje, pra não exibir os eventos passados;

2017-11-18 23:44 UTC, fnscoder commented on events/templates/events/search_events.html
> +            <p>Sorry! We don't have any event in this city or category at this moment.</p>
Ok.

2017-11-18 23:47 UTC, fnscoder commented on events/templates/events/search_events.html
> +    {% if request.method == "POST" %}
ok

2017-11-19 00:22 UTC, fnscoder commented on events/templates/events/search_events.html
> +            <form method="post">
ok

2017-11-19 20:39 UTC, fnscoder commented on events/views/search_event_view.py
> +        events = Event.objects.all()
ok

2017-11-19 22:41 UTC, fnscoder commented on events/views/search_event_view.py
> +            category = Category.objects.get(name=category)
ok

2017-11-19 22:41 UTC, fnscoder commented on events/templates/events/search_events.html
> +                        <option value="{{ city.description }}">{{ city.description }}</option>
ok

2017-11-19 22:41 UTC, fnscoder commented on events/templates/events/search_events.html
> +                        <option value="{{ category.name }}">{{ category.name }}</option>
ok

2017-11-22 02:10 UTC, merged